fyp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('fyps.urls')),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fyps/urls.py
"""定义fyps的URL模式"""
from django.urls import path
from . import views

app_name = 'fyps'

urlpatterns = [

    path('',views.index,name='index'),
    path('image/',views.upload_image,name='image'),
    path('analysis/', views.analyze_image, name='analysis'),
]

users/urls.py
"""define url pattern for application users """
from django.urls import path,include
from . import views
app_name = 'users'
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

fyps/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.db import models

class UploadedImage(models.Model):
    image = models.ImageField(upload_to='uploads/')
    upload_date = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.image.name

users/models.py
from django.db import models

# Create your models here.

fyps/forms.py
# forms.py
from django import forms

# class SegmentationForm(forms.Form):
#     image = forms.ImageField()



from django import forms
from .models import UploadedImage

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ('image',)

    def clean_image(self):
        image = self.cleaned_data['image']
        if image.content_type not in ['image/png']:
            raise forms.ValidationError("Only PNG images are allowed.")
        return image

fyps/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings
from fyps.models import UploadedImage
from fyps.forms import UploadImageForm
from fyps.segmentation import run_segmentation,run_classification
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from PIL import Image
def resize_image(image_path, target_size=(256, 256)):
    image = Image.open(image_path)
    resized_image = image.resize(target_size, Image.ANTIALIAS)
    resized_image.save(image_path)

    return resized_image


def index(request):
    """medical image analysis的主页"""
    return render(request,'fyps/index.html')

@login_required
def upload_image(request):
    if request.method == 'POST' and 'upload' in request.POST:
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_image = form.cleaned_data['image']
            uploaded_image_content = uploaded_image.read()

            # Save the resized image for display
            image_path = default_storage.save('uploaded_images/{}'.format(uploaded_image.name),
                                              ContentFile(uploaded_image_content))

            # Save the original image for segmentation
            original_image_path = default_storage.save('uploaded_images/original_{}'.format(uploaded_image.name),
                                                       ContentFile(uploaded_image_content))

            # Resize the uploaded image for display
            resize_image(os.path.join(settings.MEDIA_ROOT, image_path))

            uploaded_image_url = os.path.join(settings.MEDIA_URL, image_path)
            request.session['uploaded_image_url'] = uploaded_image_url
            request.session['original_image_url'] = os.path.join(settings.MEDIA_URL, original_image_path)
            context = {'form': form, 'uploaded_image': uploaded_image_url}
            return render(request, 'fyps/upload.html', context)
    else:
        form = UploadImageForm()
    context = {'form': form}
    return render(request, 'fyps/upload.html', context)


@login_required
def analyze_image(request):
    if request.method == 'POST':
        uploaded_image_url = request.session.get('uploaded_image_url', None)
        original_image_url = request.session.get('original_image_url', None)
        if not uploaded_image_url or not original_image_url:
            return HttpResponseRedirect(reverse('fyps:image'))

        # Remove the /media/ from the beginning of the path
        uploaded_image_url = uploaded_image_url.replace('/media/', '')
        original_image_url = original_image_url.replace('/media/', '')

        image_full_path = os.path.join(settings.MEDIA_ROOT, original_image_url)

        mask_image = run_segmentation(image_full_path)
        flag1, flag2, flag3 = run_classification(image_full_path)
        mask_image_filename = 'mask.png'
        mask_path = default_storage.save(mask_image_filename, ContentFile(mask_image.tobytes()))
        result_image_url = os.path.join(settings.MEDIA_URL, 'mask.png')

        uploaded_image_url = os.path.join(settings.MEDIA_URL, uploaded_image_url)

        classification_messages = []
        if flag1:
            classification_messages.append("ground glasses")
        if flag2:
            classification_messages.append("consolidations")
        if not classification_messages:
            classification_messages.append("healthy")

        classification = " and ".join(classification_messages)

        context = {'form': UploadImageForm(), 'uploaded_image': uploaded_image_url, 'result_image': result_image_url, 'result_image_name': mask_image_filename, 'classification': classification}
        return render(request, 'fyps/upload.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """注册新用户"""
    if request.method != 'POST':
        #显示空的注册表单
        form = UserCreationForm()
    else:
        #处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #让用户自动登陆，再重定向到主页
            login(request,new_user)
            return redirect('fyps:index')
    #显示空表单或指出表单无效
    context = {'form':form}
    return render(request,'registration/register.html',context)

fyps/templates/fyps/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
  <title>fyps</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <style>
    body {
      background-image: url("{% static 'images/background.jpg' %}");
      background-size: cover;
      background-repeat: no-repeat;
    }
    .jumbotron {
      background-color: rgba(255, 255, 255, 0.7); /* White background with 60% opacity */
    }
    .logo-container {
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .logo {
      max-height: 50px;
    }
  </style>
</head>
<body>
  <div class="container">
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a calss="navbar-brand" href="{% url 'fyps:index'%}">
      HOME</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarCollapse" aria-controls="navbarCollapse"
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fyps:image'%}">
            Upload Image</a></li>
      </ul>
      <div class="logo-container">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
      </div>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottem">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
  </div>
</body>
</html>

fyps/templates/fyps/index.html
{% extends "fyps/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Make the diagnosis!</h1>
    <p class="lead">This is a system for medical image analysis, you can upload your medical
    image to get a segmentation mask which can help you make early diagnosis.</p>
    <div class="d-flex">
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
        <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
        role="button">Login &raquo;</a>
        <a class="btn btn-lg btn-primary ml-auto" href="{% url 'fyps:image' %}"
        role="button">Upload Image</a>
    </div>
</div>
{% endblock page_header %}

fyps/templates/fyps/upload.html
{% extends "fyps/base.html" %}

{% block content %}
  <div class="jumbotron">
    <h2>Upload an image</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" name="upload" class="btn btn-primary">Upload Image</button>
    </form>

    <div class="container">
      <div class="row d-flex align-items-start">
        {% if uploaded_image %}
          <div class="col text-center">
            <h2>Uploaded Image</h2>
            <img src="{{ uploaded_image }}" class="img-fluid">
          </div>
        {% endif %}

        {% if result_image %}
          <div class="col text-center">
            <div class="card mb-2">
              <div class="card-body">
                <h5 class="card-title">Classification Result:</h5>
                <p class="card-text">{{ classification }}</p>
              </div>
            </div>
            <h2>Result Image</h2>
            <img src="{{ result_image }}" class="img-fluid">
            <div class="mt-2">
              <a href="{{ result_image }}" download="{{ result_image_name }}" class="btn btn-primary">Save File</a>
            </div>
          </div>
        {% endif %}
      </div>
    </div>

    {% if uploaded_image %}
    <form method="post" action="{% url 'fyps:analysis' %}" class="mt-2">
      {% csrf_token %}
      <input type="hidden" name="uploaded_image_url" value="{{ uploaded_image }}">
      <button type="submit" name="analysis" class="btn btn-primary">Analysis</button>
    </form>
    {% endif %}
  </div>
{% endblock %}